### ISSUE TITLE
Close Button don't work in Firefox/IE11

### ISSUE THREAD

**Issue by Eurecam-Tristan** [wiringtheworld/Snarl#17]
The close button of the snarl notification fails in Firefox, error is : "event.toElement is undefined".
After some googling it seems the solution is to replace all (line 229 and 233 in snarl.js) "event.toElement" by "event.target". After test, to me it works.

**Comment by hoxxep** [comment]
Ah, I see! This issue should be fixed in v0.3.3. Let me know if it's fixed the problem for you?

**Comment by Eurecam-Tristan** [comment]
Yep, v0.3.3 fixed the problem for Firefox. 
For IE, I have to borrow a Windows PC to test to be sure it's OK.

I have to congratulate you : this is a very nice lib without dependency to big lib (like jQuery), very useful to me. And you quickly applied fix, nice job.

**Comment by hoxxep** [comment]
Cheers! And no worries, since it's using `event.target` with a fallback to `event.toElement` it should be okay I think. :+1: 

As a sidenote: for v1.0 I'm hoping to clean it up a little by using ES6, so that each notification is it's own object and is much easier to manipulate/keep track of. So that usage looks a little more like:

```javascript
var notification = Snarl({title: 'New Notification'});
// or Snarl.open(...), or Snarl.create(...)
// so that Snarl.closeAll() and Snarl.notifications() can exist?

// editing/updating a notification
notification.edit({title: 'Updated Title'});

// checking if a notification has been dismissed (boolean true/false)
var dismissed = notification.visible(); // or .dismissed()?

// manually dismiss/close a notification
notification.close(); // or .dismiss()?
```

I'm a bit indecisive regarding the best way to structure and name functions in the new library, but if you have any suggestions I'd love to hear them.

**Comment by Eurecam-Tristan** [comment]
I'm not an expert in ES6 (never take time to learn in depth the change) but yes, it seems easier to manipulate Snarl notification.
For me an evolution that will be cool, and snarl v1.0 should be ready, is add style and have some default style to notification. Like [sweet alert](https://t4t5.github.io/sweetalert/) you have type "warning" or "success" or "error".
If in the future we can do : 
```javascript
// Create a notification to say all is okay
// Don't know if I prefer Snarl.create()
var notification = Snarl({title: 'New Notification : all is OK', type:'success'}); 

// Finally something went wrong
// this will change style and title to warn user
// NOTE: I imagine warning style can be just a background or border orange or something like this
// I'd like to have the possibility to change just icon color easily
notification.edit({title: 'Update : Ooops you should look at this', type:'warning'}); 
```
Your new version seems to be ready to add this or any properties to notifications, this is nice and edit/visible/close is okay for me.

I have just a question, maybe I'm missing something : to manage snarl notification maybe snarl could have a add/get/remove with id setting to notification ?
So we can do : 
```javascript
for (var i=1; i<5; i++) {
   Snarl.add({title: 'New Notification '+i, id:i});
}

// Change the notification number 3
// Snarl.getById can return null if notification is dismissed or don't exist
var notification_3 = Snarl.getById(3);
if (null != notification_3) {
   notification_3.edit(title: 'Edited');
}
```
Don't know if it's Snarl job to manage this. 
Note: I recently used [Raphael.js](http://raphaeljs.com/reference.html#Paper.getById) and extensively used Paper.getById().
But Raphael is SVG canvas library so all elements live in Raphael canvas, this idea maybe shouldn't be applied to Snarl.

PS: excuse my english, and sorry for long time without response
